template = "https://github.com/giellalt/template-lang-und"
rev_id = 317
template_sha = "3d0bcfa8020a96bc946192565f7e92213470a110"

[replacements]
__GLOTTOLOG_ID__ = "kiow1266"
__REPO__ = "lang-kio"
__UND2C__ = "kio"
__UNDEFINED__ = "Kiowa"
__UND__ = "kio"
