[package]
name = "kio"
human_name = "Kiowa"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.kio]
filename = "kio-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-kio"
platform = "windows"
uuid = "B177730B-D332-45D9-A2BD-ED7AFB551D5A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.kio"
package = "speller-kio"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-kio-mso"
platform = "windows"
uuid = "84AAC359-AF47-4E32-AA1A-22B61B54CDF4"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-kio"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
